name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: pdo_sqlite
        
    - name: Copy environment file
      run: cp .env.example .env

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Set up SQLite database
      run: |
        touch database/database.sqlite
        php artisan config:clear
        php artisan migrate --force

    - name: Run tests
      run: php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite